In [3]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as func
spark = SparkSession.builder.appName("total_spend").getOrCreate()

In [17]:
df1 = spark.read.csv("file:///SparkCourse/customer-orders.csv", schema="customerID int, itemID int, amount_spend float")
df1.printSchema()
df2 = df1.select("customerID","amount_spend").groupBy("customerID").agg(func.round(func.sum("amount_spend"),2))
results = df2.collect()
for result in results:
    print(f"{result[0]} \t {result[1]}")

root
 |-- customerID: integer (nullable = true)
 |-- itemID: integer (nullable = true)
 |-- amount_spend: float (nullable = true)

31 	 4765.05
85 	 5503.43
65 	 5140.35
53 	 4945.3
78 	 4524.51
34 	 5330.8
81 	 5112.71
28 	 5000.71
76 	 4904.21
27 	 4915.89
26 	 5250.4
44 	 4756.89
12 	 4664.59
91 	 4642.26
22 	 5019.45
93 	 5265.75
47 	 4316.3
1 	 4958.6
52 	 5245.06
13 	 4367.62
86 	 4908.81
6 	 5397.88
16 	 4979.06
3 	 4659.63
20 	 4836.86
40 	 5186.43
94 	 4475.57
57 	 4628.4
54 	 6065.39
96 	 3924.23
48 	 4384.33
5 	 4561.07
19 	 5059.43
92 	 5379.28
64 	 5288.69
41 	 5637.62
15 	 5413.51
43 	 5368.83
37 	 4735.2
61 	 5497.48
88 	 4830.55
9 	 5322.65
17 	 5032.68
72 	 5337.44
35 	 5155.42
4 	 4815.05
55 	 5298.09
59 	 5642.89
8 	 5517.24
39 	 6193.11
23 	 4042.65
49 	 4394.6
7 	 4755.07
84 	 4652.94
87 	 5206.4
51 	 4975.22
69 	 5123.01
97 	 5977.19
63 	 5415.15
10 	 4819.7
77 	 4327.73
50 	 4517.27
45 	 3309.38
38 	 4898.46
82 	 4812.49
80 	 4727.86
25 	 5057.61
73 	 6206.2
24 	 5259.92
70 	 5368.25
62 	 5253.32
95 	 4876.84
29 	 5032.53
21 	 4707.41
98 	 4297.26
60 	 5040.71
90 	 5290.41
32 	 5496.05
75 	 4178.5
56 	 4701.02
58 	 5437.73
11 	 5152.29
33 	 5254.66
83 	 4635.8
71 	 5995.66
68 	 6375.45
14 	 4735.03
42 	 5696.84
2 	 5994.59
79 	 3790.57
99 	 4172.29
30 	 4990.72
66 	 4681.92
46 	 5963.11
67 	 4505.79
0 	 5524.95
18 	 4921.27
74 	 4647.13
36 	 4278.05
89 	 4851.48